import type { ProjectType } from "@/interfaces/ProjectsType";

export const projects: ProjectType[] = [
  {
    id: "sixchains",
    name: "Sixchains Digital House",
    imgName: "six-chains-thumb.webp",
    projectVideo:
      "https://www.youtube.com/embed/Ki9pPLjDFRw?si=SchDFKl5NTPp3cMw",
    width: "800",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "Vue.js",
      "Nuxt.js",
      "Vuetify",
      "Tailwind",
    ],
    url: "https://sixchains.com.br/",
    repository: "",
  },
  {
    id: "mos",
    name: "MOS Consultoria",
    imgName: "mos.png",
    projectVideo:
      "https://www.youtube.com/embed/HIJjQfrDr0w?si=TeIR_2XC6t6iGLS6",
    width: "1200",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "Vue.js",
      "Nuxt.js",
      "Vuetify",
      "Tailwind",
    ],
    url: "https://mosconsultoria.com.br/",
    repository: "",
  },
  {
    id: "productsStore",
    name: "Products Store",
    imgName: "products-store.webp",
    projectVideo:
      "https://www.youtube.com/embed/OPsTn2k5vYY?si=f7cKrtCp4QIEkkrh",
    width: "900",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "Vue.js",
      "Nuxt.js",
      "Tailwind",
      "Firebase",
    ],
    url: "https://mauricio-products-store.netlify.app",
    repository: "https://github.com/mauricio071/Products-Store",
  },
  {
    id: "controlAi",
    name: "ControlAÍ",
    imgName: "controlai.webp",
    projectVideo:
      "https://www.youtube.com/embed/xs5c_POSKxg?si=GTey4efk1BefFDRC",
    width: "900",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React.js",
      "Material UI",
      "Cypress",
      "Firebase",
    ],
    url: "https://control-ai-ma.vercel.app",
    repository: "https://github.com/mauricio071/ControlAI",
  },
  {
    id: "cineLib",
    name: "CineLib",
    imgName: "cinelib.webp",
    projectVideo:
      "https://www.youtube.com/embed/PIm6l5R7FF4?si=DmC3VPX2rZzk2Itg",
    width: "800",
    technologies: ["HTML", "CSS", "JavaScript", "React.js", "SASS", "Tailwind"],
    url: "https://cinelib-ma.netlify.app/",
    repository: "https://github.com/mauricio071/CineLib",
  },
  {
    id: "cleanTube",
    name: "CleanTube",
    imgName: "cleantube.webp",
    projectVideo:
      "https://www.youtube.com/embed/P_vSeQTrbEk?si=iz7de8l1ff3a2sxK",
    width: "1000",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "Vue.js",
      "Nuxt.js",
      "Nuxt UI",
      "Tailwind",
      "PostgreSQL",
    ],
    url: "https://cleantube.vercel.app",
    repository: "https://github.com/mauricio071/CleanTube",
  },
  {
    id: "projectCosts",
    name: "Project Costs",
    imgName: "project-costs.webp",
    projectVideo:
      "https://www.youtube.com/embed/bS2nScs_zp4?si=8P-NRN8t1REkZ02G",
    width: "900",
    technologies: ["HTML", "CSS", "JavaScript", "React.js", "Node.js"],
    url: "https://project-costs.netlify.app",
    repository: "https://github.com/mauricio071/project-costs",
  },
  {
    id: "tarefasPinia",
    name: "Tarefas Pinia",
    imgName: "tarefas-pinia.webp",
    projectVideo:
      "https://www.youtube.com/embed/2UXGRnyeMpM?si=e1R3DPcBGheFCuxt",
    width: "900",
    technologies: ["HTML", "CSS", "JavaScript", "Vue.js", "Tailwind"],
    url: "https://tarefas-pinia.netlify.app",
    repository: "https://github.com/mauricio071/Tarefas-pinia",
  },
  {
    id: "sistemaAcademia",
    name: "Sistema de Academia",
    imgName: "sistema-academia.webp",
    projectVideo:
      "https://www.youtube.com/embed/gkE8k4jYrQ8?si=jkJ-VgOnqXKMecXP",
    width: "900",
    technologies: ["C#", ".NET Framework", "SQLite"],
    url: "https://github.com/mauricio071/Sistema-de-Academia/blob/master/instalador/Instalador_Academia/Instalador_sistema_academia.rar",
    repository: "https://github.com/mauricio071/Sistema-de-Academia",
  },
  {
    id: "makeYourBurger",
    name: "Make Your Burger",
    imgName: "make-your-burger.webp",
    projectVideo:
      "https://www.youtube.com/embed/mZXnsn0k59A?si=n_W2JVULpK5RTQ1R",
    width: "900",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "Vue.js",
      "Tailwind",
      "Node.js",
    ],
    url: "https://make-your-burger-ma.netlify.app/",
    repository: "https://github.com/mauricio071/Make-Your-Burger",
  },
  {
    id: "manhattanCoffee",
    name: "Manhattan Coffee House",
    imgName: "manhattan-coffee-house.webp",
    projectVideo:
      "https://www.youtube.com/embed/ucYdiPY7eI0?si=yBnM-9FqNyxPVw6K",
    width: "900",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React.js",
      "Styled Components",
    ],
    url: "https://manhattan-coffee-house-ma.vercel.app/",
    repository: "https://github.com/mauricio071/manhattan-coffee-house",
  },
  {
    id: "itSolutions",
    name: "IT Solutions",
    imgName: "it-solutions.webp",
    projectVideo:
      "https://www.youtube.com/embed/r1WmECjX9R0?si=DvGMd-n3bdmwnT_A",
    width: "900",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "TypeScript",
      "React.js",
      "Styled Components",
    ],
    url: "https://it-solutions-ma.vercel.app/",
    repository: "https://github.com/mauricio071/it-solutions",
  },
  {
    id: "appChamada",
    name: "App de chamada de alunos",
    imgName: "app-chamada.webp",
    projectVideo: "",
    width: "900",
    technologies: ["Android", "Kotlin", "SQLite"],
    url: "",
    repository: "https://github.com/mauricio071/Sistema-de-chamada",
  },
  {
    id: "jogoForca",
    name: "Jogo da Forca",
    imgName: "jogo-da-forca.png",
    projectVideo:
      "https://www.youtube.com/embed/lvqXXpjiqxU?si=2SIUBsbDpECCc2HF",
    width: "900",
    technologies: ["HTML", "CSS", "JavaScript", "Vue.js"],
    url: "https://jogo-da-forca-vue.netlify.app",
    repository: "https://github.com/mauricio071/jogo-da-forca",
  },
  {
    id: "editorTexto",
    name: "Editor de Texto",
    imgName: "editor-texto.webp",
    projectVideo:
      "https://www.youtube.com/embed/_viLGq2citw?si=5uP1UQjwhB5XZECz",
    width: "900",
    technologies: ["C#", ".NET Framework"],
    url: "https://github.com/mauricio071/Editor-de-texto/raw/master/instalador/Instalador_editor_de_texto/Instalador_editor_de_texto.rar",
    repository: "https://github.com/mauricio071/Editor-de-texto",
  },
  {
    id: "leitor",
    name: "Sistema de leitor",
    imgName: "sistema-leitor.webp",
    projectVideo: "",
    width: "900",
    technologies: ["Java", "SQL"],
    url: "",
    repository: "https://github.com/mauricio071/Sistema-de-leitor",
  },
  {
    id: "breve",
    name: "Em breve!",
    imgName: "em-breve.webp",
    projectVideo: "",
    width: "900",
    technologies: [],
    url: "",
    repository: "",
  },
];
