export const technologies = [
  { name: "HTML", color: "#e34f26" },
  { name: "CSS", color: "#264de4" },
  { name: "JavaScript", color: "#f0db4f" },
  { name: "TypeScript", color: "#3178c6" },
  { name: "Vue.js", color: "#41b883" },
  { name: "Nuxt.js", color: "#00dc82" },
  { name: "Vuetify", color: "#2196f3" },
  { name: "React.js", color: "#61dafb" },
  { name: "Material UI", color: "#007FFF" },
  {
    name: "Styled Components",
    color: "#DB7093",
  },
  { name: "Tailwind", color: "#38b2ac" },
  { name: "Bootstrap", color: "#7952b3" },
  // { name: "SASS", color: "#cc6699" },
  { name: "Jest", color: "#99425B" },
  { name: "Node.js", color: "#68a063" },
  { name: "Git", color: "#f05032" },
];
