export const tecnologias = [
  { nome: "HTML", cor: "#e34f26" },
  { nome: "CSS", cor: "#264de4" },
  { nome: "JavaScript", cor: "#f0db4f" },
  { nome: "TypeScript", cor: "#3178c6" },
  { nome: "Vue.js", cor: "#41b883" },
  { nome: "Nuxt.js", cor: "#00dc82" },
  { nome: "Vuetify", cor: "#2196f3" },
  { nome: "React.js", cor: "#61dafb" },
  { nome: "Material UI", cor: "#007FFF" },
  {
    nome: "Styled Components",
    cor: "#DB7093",
  },
  { nome: "Tailwind", cor: "#38b2ac" },
  { nome: "Bootstrap", cor: "#7952b3" },
  // { nome: "SASS", cor: "#cc6699" },
  { nome: "Jest", cor: "#99425B" },
  { nome: "Node.js", cor: "#68a063" },
  { nome: "Git", cor: "#f05032" },
];
